import type { CommunicationMessage } from "@/lib/communications";

export const DEMO_LECTURER_NOTIFICATIONS: CommunicationMessage[] = [
  {
    id: "demo-notice-release-follow-up",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    cleared: false,
    read: false,
    category: "grade-released",
    recipientName: "Dr. Demo Lecturer",
    recipientEmail: "demo@gradeai.com",
    recipientId: "demo-lecturer",
    subject: "Released result follow-up",
    body: "Released results are ready to review for the policy brief assignment.",
    relatedAssignmentId: "demo-assignment-policy-brief",
  },
  {
    id: "demo-notice-ai-ready",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    cleared: false,
    read: false,
    category: "ai-grading-ready",
    recipientName: "Dr. Demo Lecturer",
    recipientEmail: "demo@gradeai.com",
    recipientId: "demo-lecturer",
    subject: "Synthetic AI grading ready",
    body: "AI grading is ready for the policy brief assignment.",
    relatedAssignmentId: "demo-assignment-policy-brief",
  },
  {
    id: "demo-notice-1",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    cleared: false,
    read: false,
    category: "submission-received",
    recipientName: "Dr. Demo Lecturer",
    recipientEmail: "demo@gradeai.com",
    recipientId: "demo-lecturer",
    subject: "New synthetic submission received",
    body: "Amina Hassan submitted Strategic Policy Brief: Housing Affordability Interventions.",
    relatedAssignmentId: "demo-assignment-policy-brief",
  },
  {
    id: "demo-notice-2",
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    cleared: false,
    read: true,
    category: "integrity-check-ready",
    recipientName: "Dr. Demo Lecturer",
    recipientEmail: "demo@gradeai.com",
    recipientId: "demo-lecturer",
    subject: "Synthetic integrity review ready",
    body: "The demo integrity evidence pack is ready for review on the policy brief assignment.",
    relatedAssignmentId: "demo-assignment-policy-brief",
  },
];

export const DEMO_STUDENT_NOTIFICATIONS: CommunicationMessage[] = [
  {
    id: "demo-student-notice-1",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    cleared: false,
    read: false,
    category: "grade-released",
    recipientName: "Demo Student",
    recipientEmail: "student@gradeai.com",
    recipientId: "demo-student",
    subject: "Feedback released",
    body: "Your feedback for CS301 Assignment 1 - Data Structures is now available in the demo workspace.",
    relatedAssignmentId: "demo-assignment-1",
    relatedStudentId: "demo-student",
  },
  {
    id: "demo-student-notice-2",
    createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    cleared: false,
    read: true,
    category: "intervention-follow-up",
    recipientName: "Demo Student",
    recipientEmail: "student@gradeai.com",
    recipientId: "demo-student",
    subject: "Study plan reminder",
    body: "Review the complexity-analysis tasks in your improvement plan before the next submission window.",
    relatedStudentId: "demo-student",
  },
];
