server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /auth {
    add_header X-Robots-Tag "noindex, nofollow" always;
    try_files $uri $uri/ /index.html;
  }

  location = /reset-password {
    add_header X-Robots-Tag "noindex, nofollow" always;
    try_files $uri $uri/ /index.html;
  }

  location = /force-password-change {
    add_header X-Robots-Tag "noindex, nofollow" always;
    try_files $uri $uri/ /index.html;
  }

  location ^~ /dashboard {
    add_header X-Robots-Tag "noindex, nofollow" always;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
